/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Lthompson' at '6/5/16 8:30 PM' with Gradle 2.12
 *
 * @author Lthompson, @date 6/5/16 8:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
